from tkinter import *
from tkinter import font
from tkinter import messagebox
from button_appointement import *
import sqlite3
conn=sqlite3.connect('hospital.db')
c=conn.cursor()
'''c.execute("""CREATE TABLE TARUN(
            id number PRIMARY KEY NOT NULL,
            name text ,
            age number,
            mob number,
            date number,
            doctor text,
            branch text
            )""")'''


root1=Tk()
root1.title("PROJECT")
f1=Frame(root1,height=768,width=1360,bg='blue',cursor='arrow')
file2=PhotoImage(file="G:\python programs\python project\heading.gif")
file1=PhotoImage(file="G:\python programs\python project\hh.gif")
label=Label(f1,image=file2,width=750,height=266,bg="red")
label.place(x=303,y=0)
l=Label(f1,image=file1)
r=Label(f1,image=file1)
l.place(x=0,y=0)
r.place(x=1056,y=0)
b=Button(f1,text="BOOK AN APPOINMENT",width=150,height=100,font=('Arial',-12,'bold'),bg='yellow')
b1=Button(f1,text="FACILITIES PROVIDED",width=150,height=100,font=('Arial',-12,'bold'),bg='yellow')
b2=Button(f1,text="CONTACT",width=150,height=100,font=('Arial',-12,'bold'),bg='yellow')
b1.place(x=10,y=360,width=150,height=75)
b2.place(x=10,y=460,width=150,height=75)
lr=Label(f1,text="RECEPTIONIST LOGIN",width=35,height=3,font=('Times',-30,'bold italic'),bg='blue',fg='YELLOW')
lr.place(x=410,y=290)         
lu=Label(f1,text="LOGIN ID",width=10,height=2,font=('Arial',-20,'bold'),fg='black',bg='blue')
lu.place(x=450,y=410)
lp=Label(f1,text="PASSWORD",width=10,height=2,font=('Times',-20,'bold'),fg='black',bg='blue')
lp.place(x=450,y=450)
eu=Entry(f1,width=30,fg='black',bg='blue',font=('Arial',14,'bold'))
ep=Entry(f1,width=30,fg='black',bg='blue',font=('Arial',14,'bold'),show='*')
eu.place(x=590,y=410)
ep.place(x=590,y=460)
br=Button(f1,text="LOGIN",font=('Arial',14,'bold'),width=10,height=2,bg="red",fg="black")
br.place(x=625,y=510)
h1=ButtonHome(root1,f1)
def buttonclick(self):
    f1.destroy()
    root1.title("PROJECT")
    root1.geometry("1360x768")
    f=Frame(root1,height=768,width=1360,bg="blue",cursor="arrow")
    l=Label(f,text="APPOINTMENT FORM",width=20,height=3,font=('courier',-30,'bold'),fg='yellow',bg='blue')
    l.place(x=600,y=0)
    li=Label(f,text='ID:',font=('Arial',-20,'bold'),bg='blue')
    lp=Label(f,text="PATIENT DETAILS",width=20,height=2,font=('Arial',-15,'bold'),fg='yellow',bg='blue')
    l1=Label(f,text='NAME:',font=('Arial',-20,'bold'),bg='blue')
    l2=Label(f,text='AGE:',font=('Arial',-20,'bold'),bg='blue')
    l3=Label(f,text='ADDRESS:',font=('Arial',-20,'bold'),bg='blue')
    l4=Label(f,text='MOBILE NUMBER:',font=('Arial',-20,'bold'),bg='blue')
    l5=Label(f,text='EMAIL ID:',font=('Arial',-20,'bold'),bg='blue')
    l6=Label(f,text='GENDER:',font=('Arial',-20,'bold'),bg='blue')
    l7=Label(f,text='DATE',font=('Arial',-20,'bold'),bg='blue')
    l8=Label(f,text='DOCTOR NAME',font=('Arial',-20,'bold'),bg='blue')
    l9=Label(f,text='BRANCH',font=('Arial',-20,'bold'),bg='blue')
    r1=Radiobutton(f,bg='blue',fg='black',font=('Georgia',-20),text="MALE",value=1)
    r2=Radiobutton(f,bg='blue',fg='black',font=('Georgia',-20),text="FEMALE",value=2)
    e1=Entry(f,width=25,fg='black',bg='blue',font=('arial',14))
    e2=Entry(f,width=25,fg='black',bg='blue',font=('arial',14))
    e3=Entry(f,width=30,fg='black',bg='blue',font=('arial',14))
    e4=Entry(f,width=25,fg='black',bg='blue',font=('arial',14))
    e5=Entry(f,width=25,fg='black',bg='blue',font=('arial',14))
    e7=Entry(f,width=25,fg='black',bg='blue',font=('Arial',14))
    e8=Entry(f,width=25,fg='black',bg='blue',font=('Arial',14))
    e9=Entry(f,width=25,fg='black',bg='blue',font=('Arial',14))
    ei=Entry(f,width=25,fg='black',bg='blue',font=('Arial',14))
    e1.pack()
    li.place(x=100,y=100)
    l1.place(x=100,y=150)
    l2.place(x=100,y=200)
    l3.place(x=100,y=250)
    l4.place(x=100,y=300)
    l5.place(x=100,y=400)
    l6.place(x=100,y=350)
    l7.place(x=100,y=450)
    lp.place(x=50,y=50)
    l8.place(x=100,y=500)
    l9.place(x=100,y=550)
    ei.place(x=300,y=100)
    e1.place(x=300,y=150)
    e2.place(x=300,y=200)
    e3.place(x=300,y=250)
    e4.place(x=300,y=300)
    e5.place(x=300,y=400)
    e7.place(x=300,y=450)
    e8.place(x=300,y=500)
    e9.place(x=300,y=550)
    r1.place(x=300,y=350)
    r2.place(x=400,y=350)
    bs=Button(f,text="SUBMIT",width=8,height=2,font=('Arial',-20,'bold'),bg='yellow')
    bs.place(x=600,y=650)
    def buttonclick1(self):
        root2=Tk()
        root2.title("popup")
        root2.geometry('200x170')
        if(ei.get()=='' or e1.get()=='' or e2.get()==0 or e3.get()==0 or e4.get()==0 or e5.get()==0  or e7.get()==0 or e8.get()==0 or e9.get==0):
            messagebox.showinfo("Error", "Please Enter all the details")
        if((ei.get()).isdigit()==False or (e1.get()).isdigit()==True or (e2.get()).isdigit()==False or (e4.get()).isdigit()==False  or (e8.get()).isdigit()==True or (e9.get()).isdigit()==True):
            messagebox.showinfo("Error", "INVALID DATA TYPE....!")
        try:
            c.execute("INSERT INTO TARUN (id,name,age,mob,date,doctor,branch) \
                    VALUES (?,?,?,?,?,?,?)",(ei.get(),e1.get(),e2.get(),e4.get(),e7.get(),e8.get(),e9.get()))
            conn.commit()
        except sqlite3.IntegrityError:
            messagebox.showinfo("Error", "The entered ID is already present")
        else:
            f2=Frame(root2,height=100,width=100,bg="green",cursor="arrow")
            m=Message(f2,text='YOUR APPOINTMENT DATE AND TIMING WILL BE INFORMED BY MESSAGE TO PHONE NUMBER PROVIDED',font=('verdana',14,'italic'),bg='light green',fg='red')
            m.pack(side=LEFT)
            c.execute("SELECT * FROM TARUN")
            l = c.fetchall()
            print("ID\t    NAME\t  AGE \t\tMOBILE     DATE\t\tDOCTOR\tBRANCH")
            for i in l:
                for j in i:
                    j=str(j)
                    print(j+ " "*(12-len(j)),end="")
                print()
            conn.close()
            
            f2.pack()
        
    bs.bind('<Button>',buttonclick1)
    h1=ButtonHome(root1,f)
    f.pack()
def buttonclick2(self):
    f1.destroy()
    f3=Frame(root1,height=768,width=1360,bg="blue",cursor="arrow")
    l=Label(f3,text="CRITICARE HOSPITAL",width=18,height=2,font=('courier',-45,'bold'),fg='yellow',bg='blue')
    l.place(x=600,y=0)
    l1=Label(f3,text="----------------------------------------------------------------------------------FACILITIES AVAILABLE-----------------------------------------------------------------------------",width=0,height=3,font=('Times',-20,'bold'),fg='yellow',bg='BLUE')
    l1.place(x=0,y=100)
    l1=Label(f3,text="1)CT SCAN",width=0,height=3,font=('Times',-20,'bold'),fg='yellow',bg='blue')
    l1.place(x=150,y=200)
    l2=Label(f3,text="2)EYE CHECKUP MACHINE",width=0,height=3,font=('Times',-20,'bold'),fg='yellow',bg='blue')
    l2.place(x=150,y=250)
    l3=Label(f3,text="3)MRI(FULL BODY SCAN)",width=0,height=3,font=('Times',-20,'bold'),fg='yellow',bg='blue')
    l3.place(x=150,y=300)
    l4=Label(f3,text="4)X-RAY",width=0,height=3,font=('Times',-20,'bold'),fg='yellow',bg='blue')
    l4.place(x=150,y=350)
    l5=Label(f3,text="5)NORMAL HEALTH CHECK-UP",width=0,height=3,font=('Times',-20,'bold'),fg='yellow',bg='blue')
    l5.place(x=150,y=400)
    l6=Label(f3,text="6)SUGAR TEST",width=0,height=3,font=('Times',-20,'bold'),fg='yellow',bg='blue')
    l6.place(x=150,y=450)
    h1=ButtonHome(root1,f3)
    f3.pack()
def buttonclick3(self):
    f1.destroy()
    f4=Frame(root1,height=768,width=1360,bg="blue",cursor="arrow")
    l=Label(f4,text="CRITICARE HOSPITAL",width=18,height=2,font=('courier',-45,'bold'),fg='yellow',bg='blue')
    l.place(x=600,y=0)
    l1=Label(f4,text="----------------------------------------------------------------------------------------OUR BRANCHES--------------------------------------------------------------------------------",width=0,height=3,font=('Times',-20,'bold'),fg='yellow',bg='BLUE')
    l1.place(x=0,y=100)
    l2=Label(f4,text="1)ULHASNAGAR",width=0,height=2,font=('courier',-30,'bold'),fg='yellow',bg='blue')
    l2.place(x=150,y=150)
    l2=Label(f4,text="ADDRESS:Baba Namandas Nagar, Kailash Colony, Ulhasnagar, Maharashtra 421004",width=0,height=2,font=('courier',-20,'bold'),fg='yellow',bg='blue')
    l2.place(x=150,y=200)
    l2=Label(f4,text="TELEPHONE NUMBER:xxxxxxxxx",width=0,height=2,font=('courier',-20,'bold'),fg='yellow',bg='blue')
    l2.place(x=150,y=250)
    l2=Label(f4,text="2)ANDHERI (WEST)",width=0,height=2,font=('courier',-30,'bold'),fg='yellow',bg='blue')
    l2.place(x=150,y=300)
    l2=Label(f4,text="ADDRESS:Plot Number 38/39,Main Gulmohor Road,J.V.P.D,Andheri West,Juhu,Mumbai, Maharashtra 400049",width=0,height=2,font=('courier',-20,'bold'),fg='yellow',bg='blue')
    l2.place(x=150,y=350)
    l2=Label(f4,text="TELEPHONE NUMBER:022 6775 6600",width=0,height=2,font=('courier',-20,'bold'),fg='yellow',bg='blue')
    l2.place(x=150,y=400)
    l2=Label(f4,text="3)ANDHERI (EAST)",width=0,height=2,font=('courier',-30,'bold'),fg='yellow',bg='blue')
    l2.place(x=150,y=450)
    l2=Label(f4,text="ADDRESS: Plot No 516, Besides SBI, Telli Galli, Andheri East, Mumbai, Maharashtra 400069",width=0,height=2,font=('courier',-20,'bold'),fg='yellow',bg='blue')
    l2.place(x=150,y=500)
    l2=Label(f4,text="TELEPHONE NUMBER:022 2684 4000",width=0,height=2,font=('courier',-20,'bold'),fg='yellow',bg='blue')
    l2.place(x=150,y=550)
    h1=ButtonHome(root1,f4)
    f4.pack()
def buttonclick4(self):
    f1.destroy()
    f5=Frame(root1,height=768,width=1360,bg="blue",cursor="arrow")
    label=Label(f5,image=file2,width=750,height=266,bg="red")
    label.place(x=303,y=0)
    l=Label(f5,image=file1)
    r=Label(f5,image=file1)
    l.place(x=0,y=0)
    r.place(x=1056,y=0)
    de=Button(f5,text="DOCTOR DETAILS",font=('Arial',14,'bold'),width=20,height=2,bg="red",fg="black")
    de.place(x=600,y=450)
    def buttonclick6(self):
        f5.destroy()
        f7=Frame(root1,height=768,width=1360,bg="blue",cursor="arrow")
        l=Label(f7,text="DOCTOR'S DETAILS",width=0,height=2,font=('courier',-45,'bold'),fg='yellow',bg='blue')
        l.place(x=600,y=0)
        l1=Label(f7,text="---------------------------------------------EYE SPECIALIST---------------------------------------------",width=0,height=3,font=('Times',-20,'bold'),fg='yellow',bg='blue')
        l1.place(x=150,y=100)
        l2=Label(f7,text="1)Dr TARUN METHWANI",width=0,height=3,font=('Times',-20,'bold'),fg='yellow',bg='blue')
        l2.place(x=150,y=150)
        l3=Label(f7,text="2)Dr KARAN HEMDEV",width=0,height=3,font=('Times',-20,'bold'),fg='yellow',bg='blue')
        l3.place(x=150,y=200)
        l4=Label(f7,text="----------------------------------------------------B.D.S------------------------------------------------------",width=0,height=3,font=('Times',-20,'bold'),fg='yellow',bg='blue')
        l4.place(x=150,y=250)
        l5=Label(f7,text="1)Dr MANOJ BODWANI",width=0,height=3,font=('Times',-20,'bold'),fg='yellow',bg='blue')
        l5.place(x=150,y=300)
        l6=Label(f7,text="-------------------------------------------------------M.B.B.S--------------------------------------------------",width=0,height=3,font=('Times',-20,'bold'),fg='yellow',bg='blue')
        l6.place(x=150,y=350)
        l5=Label(f7,text="1)DR YASH GULABANI",width=0,height=3,font=('Times',-20,'bold'),fg='yellow',bg='blue')
        l5.place(x=150,y=400)
        l5=Label(f7,text="2)Dr TANYA MOHANANI",width=0,height=3,font=('Times',-20,'bold'),fg='yellow',bg='blue')
        l5.place(x=150,y=450)
        l5=Label(f7,text="3)Dr ASHUTOSH MATAI",width=0,height=3,font=('Times',-20,'bold'),fg='yellow',bg='blue')
        l5.place(x=150,y=500)
        h1=ButtonHome(root1,f7)
        f7.pack()
    de.bind('<Button>',buttonclick6)
    h1=ButtonHome(root1,f5)
    f5.pack()
b1.bind('<Button>',buttonclick2)
b2.bind('<Button>',buttonclick3)
br.bind('<Button>',buttonclick4)
b.pack()
b.place(x=10,y=270,width=150,height=75)
f1.propagate(0)
b.bind('<Button>',buttonclick)
f1.pack()
root1.mainloop()
